import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne } from "next/font/google";
import "./globals.css";
import Bagde from "@/components/Bagde";
import { useEffect } from "react";

const syne = Syne({
  subsets: ["latin"],
  weight:  ["500","700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.className} antialiased w-full h-full overflow-x-hidden`}
      >
        {children}
        <Bagde />
      </body>
    </html>
  );
}
