"use client"
import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import Bagde from "@/components/Bagde";
import { useEffect } from "react";

const syne = Syne({
  subsets: ["latin"],
  weight:  ["500","700"]
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const elements = Array.from(
      document.querySelectorAll("*")
    ) as HTMLElement[];
    elements.forEach((element) => {
      window.addEventListener("keypress", (e) => {
        if (e.key === "b") {
          element.classList.add("borderS");
          element.style.backgroundColor = `rgba(${Math.random() * 255},${
            Math.random() * 255
          },${Math.random() * 255},${Math.random() * 255})`;
        }
        if (e.key === "r") {
          element.classList.remove("borderS");
          element.style.backgroundColor = "";
        }
      });
    });
  }, []);
  return (
    <html lang="en">
      <body
        className={`${syne.className} antialiased w-full h-full overflow-x-hidden`}
      >
        {children}
        <Bagde />
      </body>
    </html>
  );
}
